### ISSUE TITLE
setting CDR(accountcode) in originate freezes asterisk

### ISSUE THREAD

**Issue by panitaxx** [asterisk/node-ari-client#101]
Hello, 

I have a weird problem. I set  the variables and originate this way:
```js
    let variables = {
      "CDR(accountcode)": campid+'',
      SIPADDHEADER51: `camp_id:${campid}` } 

return chan.originate({
      endpoint,
      app: 'vcc',
      timeout,
      variables,
      callerId: cid
    })
```
The variable CDR(accountcode) hangs the channel (only a kill -9  will kill asterisk). Not even a core shutdown will shutdown.  Is only this variable. 

any hints ?

**Comment by jcolp** [comment]
This is not the right place for this kind of problem. I'd suggest using the community resources, such as the forum[1] to bring up the issue. If it's determined to be a bug in issue then one can be filed on the Asterisk issue tracker[2].

[1] https://community.asterisk.org/
[2] https://issues.asterisk.org/jira

**Comment by jcolp** [comment]
I'll also add that there is already an open issue[1] with a patch up for review for this.

[1] https://issues.asterisk.org/jira/browse/ASTERISK-27460
