### ISSUE TITLE
ari.channels.record  

### ISSUE THREAD

**Issue by OnurCwiz** [asterisk/node-ari-client#102]
Bridge.record is working but when I try to record channel by channel using channel.record either it doesn't record or it says channels already recording and it doesn't add channels to bridge.

**Comment by jcolp** [comment]
You're going to need to be more specific about what you are trying to do. For example, you can't record a channel like that while it is in a bridge.

**Comment by OnurCwiz** [comment]
I am trying to use google speech cloud so i can't use bridge record because it doesn't differentiate each speaker. If i could record the conversation channel by channel i can convert the audio file to text without a problem.

**Comment by jcolp** [comment]
The snoop functionality exists for this purpose. You can snoop on the audio stream from a channel and direct it elsewhere (for example record) while that channel is doing something else (like being in a bridge). That would be what you would need to use.
