### ISSUE TITLE
music on hold stops unexpectedly after second channel leaves before the first one to join

### ISSUE THREAD

**Issue by piux** [asterisk/node-ari-client#116]
my code is similiar to the infinit bridge. The problem starts when there is more then two channels in the same  holding bridge. If a second channel enters and leaves before the first one, it will stop the music on hold on the first one.

**Comment by samuelg** [comment]
There are various methods to seek help with Asterisk. As this is more an Asterisk related question than one specific to this library, I'd suggest using the Asterisk community site[1] or the asterisk-app-dev mailing list[2].

[1] https://community.asterisk.org/
[2] http://lists.digium.com/pipermail/asterisk-app-dev/
