### ISSUE TITLE
How to set callerId using create() + dial()

### ISSUE THREAD

**Issue by mpbanna** [asterisk/node-ari-client#121]
Hello all,
I studied allot but did not find that how to set callerId to a channel using channel create() + dial()

**Comment by chadxz** [comment]
There are various methods to seek help with Asterisk. As this is more an Asterisk related question than one specific to this library, I'd suggest using the Asterisk community site[1] or the asterisk-app-dev mailing list[2].

[1] https://community.asterisk.org/
[2] http://lists.digium.com/pipermail/asterisk-app-dev/

**Comment by navdeeshahuja** [comment]
Was anyone able to figure out this?

@mpbanna can you help, please?

I am stuck here

**Comment by hishamway** [comment]
You can do this first add connectedline(num) : "number" when creating the channel. and dial it before adding to the bridge I am able to set callerId this way.
