### ISSUE TITLE
How to make a call and play a piece of audio

### ISSUE THREAD

**Issue by lianduy** [asterisk/node-ari-client#127]
I want to call an ip phone and play an audio after the call is connected.

Most urgent

**Comment by jcolp** [comment]
There are various methods to seek help with Asterisk. I'd suggest using the Asterisk community site[1] or the asterisk-app-dev mailing list[2]. Note though that there is no time frame on when or even if someone will respond.

[1] https://community.asterisk.org/
[2] http://lists.digium.com/pipermail/asterisk-app-dev/
