### ISSUE TITLE
phone is in dialing state but receiving 'StasisStart' event

### ISSUE THREAD

**Issue by mpbanna** [asterisk/node-ari-client#129]
Hello all,
when i dial call using mobile and my mobile is showing that it is in dialling  state, but i receive 'StasisStart' event.
Actually my code is according that whenever i received 'StasisStart' then do 'answer' this call and play an 'announcement' but i found above problem so unable to play 'announcement' .

And i found a strange behave that whenever i found above problem and i restart ARI connection to same app name then above problem solved and after some call i found same above issue, 
and this issue rise when call load is high, so i don't understand what is problem, so please give solution of this problem.

**Comment by jcolp** [comment]
There are various methods to seek help with Asterisk. I'd suggest using the Asterisk community site[1] or the asterisk-app-dev mailing list[2]. Note though that there is no time frame on when or even if someone will respond.

[1] https://community.asterisk.org/
[2] http://lists.digium.com/pipermail/asterisk-app-dev/
