### ISSUE TITLE
maxSilenceSeconds not detecting silence

### ISSUE THREAD

**Issue by roysinclair** [asterisk/node-ari-client#138]
Hi All

I am really hoping that someone would be able to assist me, it seems that `ari.channels.record` with `maxSilenceSeconds` is not functioning as intended.

I have tried putting the call on mute as well as putting my hand over the mic of the phone as well as adding `maxDurationSeconds`. Recording of the message is successful. 

We are using Asterisk 16.5.1

Below is how I am using the ARI's API 
` // - Record a message
  const recordMessage = async (channel, generateUUID, format) => {    
    ari.channels.record(
      {
        channelId: channel.id,
        format,
        beep: true,
        name: generateUUID,
        maxSilenceSeconds: 5,
        maxDurationSeconds: 420,
        terminateOn: '#',
      },
      (error, info) => {
        if (error) {
          logger.error('recordMessage | unable to record message the following error was reported | ${error}');
          return;
        }   
        // - Save recording
        userProgress.saveRecording(channel.id, '${generateUUID}.${format}');
      },
    );
  };`

Any help or direction would be much appreciated.

**Comment by jcolp** [comment]
This would be an Asterisk issue, not an ARI client issue. The Asterisk project provides community resources[1] as well as an issue tracker[2].

[1] https://community.asterisk.org/
[2] https://issues.asterisk.org/
