### ISSUE TITLE
ari could not restart automatically

### ISSUE THREAD

**Issue by vshg** [asterisk/node-ari-client#14]
we use ari.start('hello-world') to active/create a stasis app in asterisk, a websocket connection is established. But if network error, the websocket will be disconnected. Then calls can't be made through  ari stasis. So is there an event to check the websocket connection? or will ari stasis app be restarted automatically?

**Comment by samuelg** [comment]
I don't believe a disconnected WebSocket automatically reconnects with the current client. I'll open an issue for this. In the mean time, pull requests are welcome.

**Comment by samuelg** [comment]
PR for this can be found at #16
