### ISSUE TITLE
can't read swagger JSON 

### ISSUE THREAD

**Issue by Ali3597** [asterisk/node-ari-client#151]
I'm trying to figure out how to use this module and I'm following this example  on the official asterisk documentation 
 https://wiki.asterisk.org/wiki/display/AST/ARI+and+Channels%3A+Manipulating+Channel+State
and it just tells me that can't read swagger JSON.
It is me that is doing something wrong or just swagger dont work anymore with asterisk and in this case what is the solution how to createe an app to communicate with ari by node.js

**Comment by gtjoseph** [comment]
Which version of Asterisk are you working with?

**Comment by Ali3597** [comment]
With the 16.18.0 version

**Comment by Ali3597** [comment]
ok so thanks to you i figured out that I just didin't have the right version of asterisk and now it works 
Thank you very much !!!

**Comment by alexp193** [comment]
for which version of asterisk you change?
