### ISSUE TITLE
ws dependency not compiling in node 0.12.7

### ISSUE THREAD

**Issue by mbrooks** [asterisk/node-ari-client#27]
I got the following error when trying to npm install ari-client:

```
> ws@0.4.31 install /usr/src/app/node_modules/ari-client/node_modules/ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)

make: Entering directory '/usr/src/app/node_modules/ari-client/node_modules/ws/build'
  CXX(target) Release/obj.target/bufferutil/src/bufferutil.o
bufferutil.target.mk:90: recipe for target 'Release/obj.target/bufferutil/src/bufferutil.o' failed
make: Leaving directory '/usr/src/app/node_modules/ari-client/node_modules/ws/build'
```

It appears that the older version of ws is not compatible with node 0.12.7 seeing that I was able to build ws 0.7.2 successfully on node 0.12.7.

**Comment by samuelg** [comment]
Is this still an issue? I believe we got web socket messages working on node 0.12 which leads me to believe this is no longer an issue.

**Comment by mbrooks** [comment]
I don't think this is an issue anymore

**Comment by samuelg** [comment]
Thanks!
