### ISSUE TITLE
Swagger API deprecated message

### ISSUE THREAD

**Issue by PhilMDev** [asterisk/node-ari-client#3]
I've searched for this all I can.  I can't seem to locate anything other than how it may be fixed.  When I load a program with ari-client I get the message:

[ 'This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info' ]

It does appear that ari-client is using ver 1.2 which is the latest.  And it's setting "swaggerVersion": "1.2" which also appears to be the correct setting.

Should I just ignore this?

Thank you!

**Comment by viebig** [comment]
Hi!
Should I just ignore after 4 years ?

**Comment by erickcrus** [comment]
No, for 7 years! rsrsrs

**Comment by Mdhaker** [comment]
What to do now after 9 years ?

**Comment by RizeKishimaro** [comment]
Please I don't want to see red alert message on my terminal.

**Comment by lscorrea** [comment]
a pergunta é, consigo atualizar o swagger manualmente ou isso geraria algum problema se sim qual caminho? obrigado!

**Comment by bkremenovic** [comment]
What to do now after 11 years ?

**Comment by jefaokpta** [comment]
same alert, keep going
