### ISSUE TITLE
ws build failure on win10 x64

### ISSUE THREAD

**Issue by drahnieR** [asterisk/node-ari-client#42]
there're a lot of errors blocking the build of this module, e.g.

> \node_modules\ari-client\node_modules\ws\node_modules\nan\nan.h(213):
error C2039: 'ThrowException': is not a member of 'v8' 
error C2039: 'New': is not a member of 'v8::String' 
error C3861: 'New': identifier not found 

upgrade ws to the latest version 1.1.0 will solve this on my end.
possible to update the dependencies?

**Comment by samuelg** [comment]
ws upgraded to 1.1.1.
