### ISSUE TITLE
Event handler leak

### ISSUE THREAD

**Issue by jaunis** [asterisk/node-ari-client#43]
There is a kind of "memory leak" in the list of event handlers (the ```_instanceListeners``` attribute of the client object): if event handlers are registered on a channel, they are kept in memory event when the channel no longer exists.

Of course, this can be avoided by explicitly calling the method ```removeAllListeners``` with the previously used events just before the channel disappears, but this behaviour is really unexpected.

If there is no general way to solve this issue, I think it should at least be documented.

**Comment by samuelg** [comment]
I agree that this should be documented. Even if the library handled channel and bridge events, there are resources that do not "go away" and would need to be handled different by the application code itself.

Also, event listeners on the client itself are for all instances of a given resource and need to be cleaned up.

Having said that, I am planning to push a PR soon to at least handle resources like bridges, channels, recordings, and the like that can be auto cleaned up by the library. I'll also add more documentation on event handlers.

Thank you for the feedback.

**Comment by lucassoler** [comment]
Same issue, we need to manually delete all events listeners. Thanky you, this may be the source of our memory leak.

**Comment by jp1987** [comment]
@lucassoler, did you ever find your memory leak?

**Comment by lucassoler** [comment]
Hi @jp1987, The memory leak was caused by events declared on channels. I needed to remove all listeners on events I instancied, at the end of the call. ("channel.removeAllListeners('ChannelDtmfReceived');" for exemple)
Since I do that, I didn't have any problem on this point.

**Comment by jp1987** [comment]
Thanks, just trying to hunt a leak on our side as well.
