### ISSUE TITLE
 Error determining real directory for rest-api

### ISSUE THREAD

**Issue by HERRKIN** [asterisk/node-ari-client#52]
I am not sure if it belongs here but it felt natural for me to put it here. I am running asterisk 13 on ubuntu 16. I enabled ari but when I try to use ari-client it says  Error determining real directory for rest-api if I go to the web browser and try ari it says the same. it lets me in with user and password but then it wont serve the api.

**Comment by chadxz** [comment]
Looks like there's something wrong with your the way your Asterisk server is compiled or configured. I'm not sure exactly what would cause this, but here's the relevant source code where that error occurs https://code.asterisk.org/code/browse/~br=14.0/asterisk/res/res_ari.c?r=e773e3a9bbaf378d53647e4bac3ffcd61afb4ae6#to606

Your best bet would be to post on the Asterisk community forum to get it sorted out. https://community.asterisk.org/

Feel free to post back here if you don't get any answer over there

**Comment by chadxz** [comment]
for what it's worth, the directory that it's looking for exists on my asterisk box as /var/lib/asterisk/rest-api. There are files there named:

```
applications.json  bridges.json   deviceStates.json  events.json     playbacks.json   resources.json
asterisk.json	   channels.json  endpoints.json     mailboxes.json  recordings.json  sounds.json
```

**Comment by HERRKIN** [comment]
I only installed it via 'sudo apt-get install asterisk' in ubuntu, this is what I have in /var/lib/asterisk/
astdb.sqlite3  moh  sounds  sqlite.db

**Comment by minooei** [comment]
installing from apt repo may not be last version 
try installing last version from source 
cheers
