### ISSUE TITLE
Swagger Client Out of Date

### ISSUE THREAD

**Issue by adamgoose** [asterisk/node-ari-client#61]
> [ 'This API is using a deprecated version of Swagger!  Please see http://github.com/wordnik/swagger-core/wiki for more info' ]

Getting this output any time the client is instantiated.

**Comment by chadxz** [comment]
The API that it's referring to in that message is the server, not the client. Astricon 2016 is this week, and there is supposed to be some discussion about what to do with respect to this at the AstriDevCon. See [this asterisk-dev mailing list discussion](http://lists.digium.com/pipermail/asterisk-dev/2016-February/075313.html)

**Comment by adamgoose** [comment]
Ah, sounds good. Just thought I'd point it out. Thanks for the info. :)

**Comment by davehorton** [comment]
still open in asterisk 16..
