### ISSUE TITLE
adding multiple channels to a bridge

### ISSUE THREAD

**Issue by timeens** [asterisk/node-ari-client#65]
How to add multiple channels by sending only one request.

"channel (string) - Ids of channels to add to bridge" -> Cannot add multiple channels using a comma separated string.

**Comment by chadxz** [comment]
which api are you trying to use?

**Comment by samuelg** [comment]
The library method supports passing an array:

```js
bridge.addChannel({ channel: ['id1', 'id2'] });
```

Hope that helps.
