### ISSUE TITLE
redirect doesnt work

### ISSUE THREAD

**Issue by Freundschaft** [asterisk/node-ari-client#72]
whats supposed to happen if I redirect the channel?

I'm using

```
incoming.redirect({endpoint: 'SIP/sip-trunk/123456789'})
                .then(function () {
                        console.log('worked');
                })
                .catch(function (err) { console.log(err);});

and its only showing 'worked' in the console without actually doing something on the call.
Am I getting something wrong here?
```

Thanks & Cheers
Qiong

**Comment by samuelg** [comment]
That means that sending the redirect to Asterisk via ARI worked, not that the redirect itself worked. I would suggest look at the Asterisk logs to see what is going on.

Please note that the redirect itself is the responsibility of Asterisk itself, and not the client library. I would suggest asking the Asterisk Developer's Mailing List [1] if you need more help with this.

[1] http://lists.digium.com/mailman/listinfo/asterisk-dev

**Comment by Freundschaft** [comment]
thanks!
