### ISSUE TITLE
Listen to multiple instanses

### ISSUE THREAD

**Issue by bozhkos** [asterisk/node-ari-client#82]
Hi. In my small project become necessary listen multiple ARI instances same time, and interact with it. And now, i really don't have any idea how to realize this feature. Can you get me something like advice, or something like that? I don`t asking for working code, just for advice.

Thanks.

**Comment by samuelg** [comment]
We support multiple Stasis apps per client using ```client.start(['app1', 'app2'])``` but connecting to multiple instances of Asterisk using a single client is not supported. You would have to keep track of multiple clients in order to do this.
