### ISSUE TITLE
how to set argument  and get argument value

### ISSUE THREAD

**Issue by mpbanna** [asterisk/node-ari-client#88]
hello,
How to set argument value in channel.orginate() and how to get argument value in ari.on('StasisStart',function(){});

**Comment by lucassoler** [comment]
channel.originate(
    {endpoint: 'SIP/1000', app: 'application', appArgs: 'yourargument'},
    function (err, channel) {}
);

**Comment by mpbanna** [comment]
ok, then how to get argument value in ari.on('StasisStart',function(){});

**Comment by lucassoler** [comment]
Hello,

channel.originate(
    {endpoint: 'SIP/1000', app: 'application', appArgs: 'yourargument'},
    function (err, channel) {}
);

ari.on('StasisStart',function(event, channel){
     var arg = event.args;
});

**Comment by mpbanna** [comment]
Thanks, it working.

**Comment by samuelg** [comment]
Thanks for the quick reply @lucassoler
