### ISSUE TITLE
ARI nodejs websocket bandwidth uses too high 

### ISSUE THREAD

**Issue by rcsarv** [asterisk/node-ari-client#89]
Hi There,
Asterisk WebSockets are using lots of bandwidth between servers. On 800 concurrent calls, it's using 315 Mbps data transfer.
Is it ok, am I missing something? 
Please suggest how to reduce bandwidth uses.

Thanks a Lot...

**Comment by samuelg** [comment]
This library is a consumer of the WebSockets used by ARI, there's not much we can do here other than recommend you use multiple Asterisk instances to spread the load.

I would recommend the app-dev mailing list[1] for this. Hope that helps.

[1] http://lists.digium.com/cgi-bin/mailman/listinfo/asterisk-app-dev
