### ISSUE TITLE
Difference between " channel.originate() " and " channels.create()+channels.dial() "

### ISSUE THREAD

**Issue by mpbanna** [asterisk/node-ari-client#92]
Hello ,
is ari.channels.create() actually originate a call, OR, a call will originate only when use ari.channels.create() then ari.channels.dial()

**Comment by jcolp** [comment]
A call will only be sent to an endpoint once dial is executed. Create does just that, creates it within Asterisk but does not dial the endpoint. There's a blog post[1] which might provide more information for you.

[1] http://blogs.asterisk.org/2016/08/24/asterisk-14-ari-create-bridge-dial/

**Comment by samuelg** [comment]
Thanks @jcolp

**Comment by mpbanna** [comment]
Hello,
I have face a new issue that is when i originate call by ari.channels.create(); function then event named 'StasisStart' will fire when phone picked , But when i originate a call by create() + dial(), then event named 'StasisStart' will not fire when phone picked, but fired when dial(); function execute.
