### ISSUE TITLE
endpoints.sendMessage triggers CLI errors on 15.0.0-rc1

### ISSUE THREAD

**Issue by capouch** [asterisk/node-ari-client#95]
This request:  `http://asterisk.example.com:8088/ari/endpoints/sendMessage( { from: from_param, to: to_param, body: body_param} )`

Works fine on 14.6.2.

On 15.0.0-rc1 the CLI shows this:
`Asterisk Ready.
[Sep 28 17:43:22] ERROR[21629]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21631]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21632]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21635]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21636]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21633]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21634]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21637]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21639]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21638]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21640]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21641]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor
[Sep 28 17:43:22] ERROR[21642]: tcptls.c:780
ast_tcptls_close_session_file: ast_tcptls_close_session_file invoked
on session instance without file or file descriptor`

I have verified that the error occurs only when that API is called through the ari-client package, the following command works silently on both versions:

`curl -v -u user:pass -X PUT "http://asterisk.example.com:8088/ari/endpoints/sendMessage?from=sip:8006&to=sip:8005&body=Now%20I%20am%20there"`

**Comment by capouch** [comment]
After some more testing, it looks like these errors occur after almost access to all the ARI resources exposed through ari-client.

**Comment by jcolp** [comment]
This message is harmless and has already been[ changed to a debug message in 15.0](https://gerrit.asterisk.org/#/c/6498/). If you are experiencing other problems then that would be separate.
